### ISSUE TITLE
DeFi cooperation talks with Zenlink and Solarbeam

### ISSUE THREAD

**Issue by h4n0** [litentry/research-force#125]
Discuss the further cooperation plan with  Zenlink and Solarbeam on Moonriver network, after XCM is established.

**Comment by qiuhaiguo** [comment]
#### Summery the talk with Zenlink for cooperation：
- The TVL of the Zenlink pool is about 40 M, and the average daily trading volume is about 2M.
- They support Moonriver, Moonbeam, and Bifrost parachain. We can build our pool on Moonriver.
- Our cross-chain token(xcLIT) will automatically be added to the Zenlink support token, once our XCM is ready.
- Zenlink's code passed a security audit by SlowMist and there were no security issues.
- Zenlink suggests us to build an xcLIT-MOVR pair, because later they will support MOVR-stableCoin pool so that the router based on the xcToken-MOVR-stableCoin has more depth for trading.
- [Guid to create a trading pair on Zenlink](https://www.notion.so/litentry/How-to-create-a-pair-on-Zenlink-a1d1b90f2b734879b30c350187a44108)

**Comment by qiuhaiguo** [comment]
#### Summery the investigation of Solarbeam：
- The TVL of the Zenlink pool is about 19M USD, and the average daily trading volume is about 0.26M USD.
- The Solarbeam is built based on Moonrive which is an EVM compatible network.
- Solarbeam has a complete line of Defi products including swap, farming, liquidity staking, bridge, etc. 
- Security audits completed by Certik and Haechi
- [How to create liquidity pairs on Solarbeam](https://www.notion.so/litentry/How-to-create-liquidity-pairs-on-Solarbeam-733a9ad1365a4ea5a7b94dac98d970e1)
