### ISSUE TITLE
Setup a basic grafana + prometheus monitor system for parachain

### ISSUE THREAD

**Issue by h4n0** [litentry/research-force#8]
We should set up a grafana configuration to monitor the metrics from parachain prometheus port.

First step is to use a standard/basic setup to cover the machine info (CPU, network usage, RAM ...) as well as polkadot-specific metrics (similar to validators).

Tasks:

- [x] migrate grafana/prometheus to a new machine (the old host has only 8G RAM)
- [x] use grafana 8.3
- [x] renew the dashboard for current validators based on https://grafana.com/grafana/dashboards/13840
- [x] setup the dashboard for parachain
- [x] setup alert rules and notifications

**Comment by Kailai-Wang** [comment]
Update:
I extend the `Estimate` to 3 because after discussion with @chenzongxiong we realized that the current grafana host is laggy and fully stressed with all the applications running on it: it has 8G RAM only.

We decide to migrate/relocate the monitoring system to a new host that is currently vacant now. The deprecated grafana dashboards need to be tidied up too.

**Comment by Kailai-Wang** [comment]
Update with task list

**Comment by Kailai-Wang** [comment]
Basically finished, some miscs are still to be discussed with @chenzongxiong 

![image](https://user-images.githubusercontent.com/7630809/145125613-d95ef0d4-0422-4b58-a437-5d278a74e883.png)

**Comment by Kailai-Wang** [comment]
PR in devops repo submitted.
Move to Review
