### ISSUE TITLE
[DevOps & Test] Test parachain with transaction loads

### ISSUE THREAD

**Issue by h4n0** [litentry/research-force#9]
In the staging parachain environment, we need to observe the actual transaction loads. The transaction we need to produce in our staging should be categorized as follows,

- [x] Complete a testing script, with which we can manually test intensive balance transfers and chain bridge transactions (open to further functionality transactions) and observe the performance on a ready-to-onboard environment
- [x] Perhaps this script can be integrated into Rundeck(how?).
- [ ] Report for better understanding the result
- [x] Maybe ask Phala about their related test

**Comment by chenzongxiong** [comment]
The scripts will be triggered every 5 minutes, and post status in slack channel **#parachain-staging-tests**

**Comment by chenzongxiong** [comment]
change from every 5 minutes from 30 seconds

**Comment by chenzongxiong** [comment]
@h4n0 @Kailai-Wang 
As for Phala feedback, they observed the console logs produced by parachain. 
No concrete metrics like, 

100 tx/s, CPU loads/memoryloads/network usage/
1000 tx/s, CPU loads/memoryloads/network usage/
etc

From my perspective, I think Han can follow the #49, then we write a script to grab the CPU/memory loads every seconds (or from grafana dashboard). 

The only tasks is to keep parachain at specific transaction loads. (HERE I treat all tx are the same, no matter how long they're executed. ). For the specific tx loads, this can be configured by rundeck approximately since we know how many tests (tx) we run. 

In the future, we may categorize different extrinsics and analysis their throughputs.

**Comment by h4n0** [comment]
A new story #76 has been created to deal with the follow-up tasks.  This issue is therefore closed.
